version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Planning Terraform"
      - terraform plan
      - echo "Applying Terraform"
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
